### PR TITLE
rxjs 5.5.0 support

### PR DESCRIPTION
**Pull request by Ronsku**

### CODE REVIEW

**Comment by Ronsku** [comment]
Since this is a breaking change version should actually be bumped up to `1.0.0`.
Observables between rxjs 5.4 and 5.5 does not match anymore. You get this error:
screen shot 2017-09-24 at 15 23 57
on old rxjs 5.4 with `getLoadingStarted: store.select(s => s.loading.started),` when trying to match it to a rxjs 5.5 `Observable<boolean>` (`loading.started` is obviously a `boolean` as well).

This closes issue #7

**Comment by Dynalon** [comment]
Ah didn't see that pull request before I commented on issue #7, sorry. 

There are also the changes for the devDependencies which have already landed in v0.1.8.

If using lettable operators would result in a breaking change that you cannot use `reactive-state` with rxjs versions <= 5.4 I might think twice before accepting this PR. The saved bytes might not be worth breaking compatibility, especially since lettable operators are not even stable right now.

When RxJS 5.5 is out I will bump my side projects and see if this is a major change, and then revisit this PR.

**Comment by Dynalon** [comment]
To add to the discussion: I would really want the latest version of `reactive-state` to be compatible with RxJS <= 5.4 and everything >= 5.5 at the same time. I am unsure if this is possible, I will have to dig into that when RxJS 5.5 is out.

**Comment by Dynalon** [comment]
Ok I had this MR merged and tested (with a publish to version 0.1.9 which should now be considered broken and superseeded by 0.1.10). Unfortunately, when pulling reactive-state from the npm repo, the error you reported pops up. This means that for any rxjs 5.4.x user this will break things. (First I suspected issues with npm link so I had to make a release with your changes).

I thus reverted back the merge, and published the fixed 0.1.10 which uses the old approach and won't break compatibility. The changes are kept in the `rxjs5.5` branch, thats where we should focus development on this matter.

For now I defintely will use the old operator approach if this means that we will we compatible to rxjs 5.4.x users. I am unsure if we break things for 5.5.x users, but I think this should not be the case.

In this case, compatiblity is more important than a few saved bytes. If we can manage to use the lettable operators and not break compatibility, I would gladly merge it in.

**Comment by Dynalon** [comment]
Alternate: If we can somehow express that rxjs5.5 is required during install (best case is show an npm message "You need rxjs5.5 for this release of reactive-state. you can use reactive-state@0.1.10 with older rxjs versions" I would also consider updating.

The whole rxjs5.4 vs. rxjs5.5 will bring a big mess to my side project, as I have a lot of private npm modules together with npm link, and I need to bump all to rxjs5.5 at the same time. I think other users have similar issues, so maybe wait a little until rxjs5.5 has been out for a while and proven ready for production. I definetely do not want to force users to update to rxjs5.5 just because of reactive-state.

**Comment by Ronsku** [comment]
Thanks for your response!

This sounds definitely smart. Let's keep rxjs5.5 in a separate branch and consider a reactive-state release for it when 5.5 is stable.

I'm also not sure if it's possible at least in a smart way to support both rxjs5.4. and rxjs5.5 at the same time. Let's stick with the branch of rxjs5.5 for now.

**Pull request merged**
